doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # url: mysql://%env(user)%:%env(secret)%@%env(host)%/%env(dbname)%?serverVersion=5.6
        override_url: true
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # if the url option is specified, it will override the above config
        # url:                  mysql://db_user:db_password@127.0.0.1:3306/db_name
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
